### ISSUE TITLE
`MapillaryDataset` can't be instanciated anymore with unaggregated labels

### ISSUE THREAD

**Issue by delhomer** [Oslandia/mapillary_classification#83]
`python deeposlandia/datagen.py -D mapillary -s 192` gives the following error:
```
Traceback (most recent call last):
  File "deeposlandia/datagen.py", line 85, in <module>
    train_dataset = MapillaryDataset(args.image_size, config_path)
  File "/home/rde/src/deeposlandia/deeposlandia/dataset.py", line 178, in __init__
    self.build_glossary(glossary_filename)
  File "/home/rde/src/deeposlandia/deeposlandia/dataset.py", line 199, in build_glossary
    label['evaluate'], category, label["contains_id"],
KeyError: 'contains_id'
```

The glossary can not be built as it expects some keys that are missing in input configuration file. These keys correspond to aggregated case.

A case distinction must be done during the process regarding the label aggregation status.

**Comment by delhomer** [comment]
Fixed by PR #82
